### PR TITLE
ES upgrades & minor cleanup

### PR DESCRIPTION
**Pull request by dpb587**
Upgrades elasticsearch to 1.7.1 (from 1.6.0) and logstash to 1.5.3 (from 1.5.2). Also cleans up the e2e test from some prior PRs and fixes some old references in readme.

Waiting on validation before merging...
- [x] e2e
- [x] meta
- [x] cityindex

### CODE REVIEW

**Comment by mrdavidlaing** [comment]
@dpb587 - Feel free to update meta.logsearch with this...

**Comment by dpb587** [comment]
On meta, an issue arose surrounding SSL handshakes. I reverted the logstash back to 1.5.2 and referenced the upstream issue in the commit. For now, we need to wait for 1.5.4.

**Comment by dpb587** [comment]
Actual logstash issue is https://github.com/elastic/logstash/issues/3657

**Comment by mrdavidlaing** [comment]
@dpb587 Nice catch!

I think its worth completing this PR (without the logstash upgrade); since the other changes still have value.

**Comment by dpb587** [comment]
Good idea. I've removed the logstash commits and forced pushed. Still need to test on cityindex before merging.

**Pull request merged**
