### PR TITLE
Add logstash-forwarder

### PR DESCRIPTION
**Pull request by dpb587**
This adds support for forwarding the elasticsearch request logs into another deployment (like we have setup on the old, active cluster).

I suppose we could make it forward every single monit stdout/stderr log and every other vcap-related log file, but I wasn't sure if we want to do that?

http://kibana-meta-logsearch-io.monitor-cloud.cityindextest5.co.uk/index.html#dashboard/temp/QDoiH4UWR9q8VhAB8z4L7w

### CODE REVIEW

**Comment by dpb587** [comment]
@mrdavidlaing, thoughts and review comments?

**Comment by dpb587** [comment]
@mrdavidlaing, I committed changes for the proposal, but had two problems.
1. You were right that the file-based key name didn't work with bosh, so it's what you originally said.
2. I tried putting both global and job-specific log paths, but the job-specific ones were the only ones which got applied. I'm not sure recursive merging works in this particular way. Feel free to take a look and tell me it actually does work and how :)

I included the logstash paths in the `bosh-lite.yaml`, but it does not include the `logstash_forwarder` job (since it requires host/cert config).

**Comment by mrdavidlaing** [comment]
@dpb587 - I've asked the bosh-users mailing list for clarrification on global + job property merging

https://groups.google.com/a/cloudfoundry.org/d/msg/bosh-users/AGkpihXWzOY/MRzEkIKGCQEJ

**Comment by dpb587** [comment]
The mailing list confirms the global/job property merging I saw as expected behavior.

**Comment by mrdavidlaing** [comment]
Bummer.

I guess if we leave it as is you can choose to use global OR job properties, which has some value.

When overriding you would be forced to respecify all paths.

**Comment by dpb587** [comment]
Alternatively, we have two properties: `logstash_forwarder.global_paths` and `logstash_forwarder.job_paths`. Confusing or worthwhile?

**Comment by mrdavidlaing** [comment]
Worthwhile.  Lets do that

**Comment by aristotelesneto** [comment]
Is logstash_forwarder lumberjack? If so I'd have switched the naming to: for the job simply "forwarder"; for the package the job uses simply "lumberjack" in order to maintain consistency with the other names.

Although I'd switch log_parser to just parser, just to take care of my itching OCD :D

**Comment by dpb587** [comment]
The forwarder [project](https://github.com/elasticsearch/logstash-forwarder) was initially and simply named `lumberjack`, but semi-recently transitioned to being called `logstash-forwarder`. The protocol maintains the name `lumberjack`, but the program we're using to forward logs is now called `logstash-forwarder`. From that perspective, I think the naming used here is consistent with the external concepts that people may already be familiar with, but we can reconsider if there's a better approach for us and logsearch users.

You might be right on the `log_parser` vs `parser` thing... hmm. @mrdavidlaing, thoughts on whether we can/should rename `log_parser` to `parser`?

**Comment by aristotelesneto** [comment]
I see, didn't realise lumberjack had been renamed. In that case, you're absolutely right, the package should be named 'logstash-forwarder'.

I'd still maintain that the logsearch bosh release job, however, should be named 'forwarder' as that would more accurately reflect bosh jobs (which can be seen as roles, which are collection of one or more packages, irrespective of each package name) and ties in better with the rest of the release - we'd have forwarder, ingestor, queue, parser, search/store, api.

Just my 2c.

**Comment by mrdavidlaing** [comment]
>  thoughts on whether we can/should rename log_parser to parser?

Sorry for being so late to the party.  A PR renaming `log_parser` to `parser` is going to get a :+1: from me

**Pull request closed without merging**
