### PR TITLE
Fixed hash in relp input add_field

### PR DESCRIPTION
**Pull request by t2sa**
repl ingestor starts fine after this fix.

### CODE REVIEW

**Comment by adasolcan** [comment]
Thanks for this!

**Comment by mrdavidlaing** [comment]
@t2sa - I can't seem to find a Contributor's License Agreement from you - see https://github.com/logsearch/licensing for details - are you submitting this change as an individual or part of a company?

Feel free to contact me on dlaing@pivotal.io if you'd prefer to have this conversation in private.

**Comment by mrdavidlaing** [comment]
@t2sa I'm sorry; but we've had to "unmerge" this PR until we get a signed CLA from you.  As soon as we have that on file we'll merge this PR again.

**Comment by mrdavidlaing** [comment]
Resolved by separate PR without CLA problems - https://github.com/logsearch/logsearch-boshrelease/pull/232

**Pull request merged**
