### PR TITLE
Create major release logsearch-1-1

### PR DESCRIPTION
**Pull request by mrdavidlaing**
- Purges old releases and blobs - NB - you cannot revert to an earlier `logsearch-n` release` after this point
- Creates new `logsearch-1` major release name
- Creates new `logsearch-1-1` release

Changes from `logsearch-13`:
- Remove S3 credentials and encryption keys

### CODE REVIEW

**Comment by dpb587** [comment]
The `logsearch-1-1` seems like an odd convention for us to maintain, but really I'm happy with any solution that will easily work. So should we just go with this?

**Comment by aristotelesneto** [comment]
I too find it odd to have 'logsearch-1'. How about 'ls'? 

I don't imagine it causing any problems, but it's worth testing upgrading a system between the two releases, to ensure that everything behaves as expected.

**Comment by mrdavidlaing** [comment]
I was thinking that `logsearch-1-1/2/3/4/5...` would allow us to have `logsearch-2-1/2/3/4/5` if we needed to do this kind of "blob purge" again

**Comment by aristotelesneto** [comment]
Makes sense. FYI, BOSH has recently [introduced changes to release versioning](https://groups.google.com/a/cloudfoundry.org/forum/#!topic/bosh-users/x43XGNLgnCA). I wonder if we could leverage that for this use case?

**Comment by mrdavidlaing** [comment]
Good to know about BOSH's new release versioning enhancements; although in this case I don't think it would help us; since we're "hacking" a major version number into the release name to prevent blob conflicts with old releases.  (ie, we want to change the release name; rather than the version)

**Comment by dpb587** [comment]
Locally, would it be reasonable and possible to:
1. locally rename [whatever release version your deployment is currently on] to `logsearch-old`
2. upload it to bosh
3. update manifest switching the release name from `logsearch` to `logsearch-old`
4. deploy (theoretically no changes would be made since it's the same blobs and resultant jobs)
5. `delete release` all the old `logsearch` versions
6. upload the already committed release 13
7. switch manifest back to `logsearch` from `logsearch-old`, upgrade version
8. `delete release` the `logsearch-old`

Then we'd have a migration path, wouldn't need to mess with `logsearch-*` in the pseudo-versioned release name (which overnight I've grown less of a fan of), and wouldn't need to make further changes to the repository.

**Comment by mrdavidlaing** [comment]
@dpb587,

Why don't you implement [your idea above](https://github.com/logsearch/logsearch-boshrelease/pull/46#issuecomment-46569058) as a separate PR; and then we know if its viable.

What we're looking for is the easiest upgrade path for people running `logsearch-13` (encrypted blobs) to `logsearch-v.unencryptedblobs`

**Comment by dpb587** [comment]
Okay, I ran through my idea (doesn't require a PR) and I think it'll work quite well. Below are all the steps I went through (since my last idea didn't fully pan out, maybe you can see if I missed a step here). Basically, I created a new VM, uploaded the old, encrypted release, transitioned to the new, unencrypted release, then made sure regular development could continue like normal.

```
# workspace
$ mkdir /tmp/logsearch

# create new bosh
bosh-lite$ vagrant destroy
bosh-lite$ vagrant up
bosh-lite$ bosh upload stemcell bosh-stemcell-3-warden-boshlite-ubuntu-trusty-go_agent.tgz

# emulate a previous cluster (assume it was running v12 which is pre-blob changes)
logsearch$ git clone git@github.com:logsearch/logsearch-boshrelease.git .
logsearch$ git checkout v12
logsearch$ bosh upload release releases/logsearch-12.yml
logsearch$ bosh -d examples/bosh-lite.yml deploy
logsearch$ tail -f /var/log/system.log | rake lumberjack:forward_stdin_to_bosh_lite
logsearch$ wget -qO- 'http://10.244.2.6:9200/_all/_search?q=*' | jq -r '.hits.total' # 117

# shift the deployment over to a temporary release
logsearch$ sed -e 's/name: logsearch/name: logsearch-old/' releases/logsearch-12.yml > releases/logsearch-old-12.yml
logsearch$ bosh upload release releases/logsearch-old-12.yml
logsearch$ sed -i '' -e 's/^- name: logsearch/- name: logsearch-old/' -e 's/release: logsearch/release: logsearch-old/' examples/bosh-lite.yml
logsearch$ bosh -d examples/bosh-lite.yml deploy
logsearch$ wget -qO- 'http://10.244.2.6:9200/_all/_search?q=*' | jq -r '.hits.total' # 117

# remove traces of the old release
logsearch$ bosh delete release logsearch

# upload logsearch v13 which is post-blob changes
logsearch$ git checkout v13
logsearch$ git clean -d -f -x .final_builds/
logsearch$ bosh upload release releases/logsearch-13.yml

# switch the deployment over to the regular release
logsearch$ git checkout examples/bosh-lite.yml
logsearch$ bosh -d examples/bosh-lite.yml deploy
logsearch$ wget -qO- 'http://10.244.2.6:9200/_all/_search?q=*' | jq -r '.hits.total' # 117
logsearch$ wget -qO- 'http://10.244.2.6:9200/' | jq -r '.version.number' # 1.0.1

# remove traces of the old temporary release
logsearch$ bosh delete release logsearch-old
logsearch$ rm releases/logsearch-old-12.yml

# now try a future release
logsearch$ git remote add patchy -f file://$HOME/code/logsearch-boshrelease
logsearch$ git checkout patchy/upgrades
logsearch$ # add my new blobs for upgrades
logsearch$ rake dev_release:create_and_upload
logsearch$ bosh -d examples/bosh-lite.yml deploy
logsearch$ wget -qO- 'http://10.244.2.6:9200/_all/_search?q=*' | jq -r '.hits.total' # 117
logsearch$ wget -qO- 'http://10.244.2.6:9200/' | jq -r '.version.number' # 1.2.1
logsearch$ bosh create release --final --force --dry-run
```

So, I think this is a viable option and, pending @mrdavidlaing's approval, we can verify it on meta.

**Comment by mrdavidlaing** [comment]
@dpb587 - looks like a workable plan to me - its basically a set of detailed steps you need to go through to upgrade from `logsearch-12` to `logsearch-13`; and should thus be documented in the [release notes for `logsearch-13`](https://github.com/logsearch/logsearch-boshrelease/releases/tag/v13)

However, if you are starting on `logsearch-13`\+ then you don't need to do anything special.

Lets try it on meta.

**Comment by dpb587** [comment]
It's frustrating when things things work differently for inexplicable reasons despite following the exact same steps and you don't know why or how to workaround. On meta, the release gets uploaded, but during compilation in the deploy it errors due to stale checksums...

```
  Started compiling packages > java7/dfe63d2af78a9f2be8bb2390dc2022ad1a2e3c4a. Failed: Action Failed get_task: Compiling package java7: Fetching package java7: Fetching package blob fd03d386-6419-477d-a0aa-2d79190b3872: SHA1 mismatch. Expected db38454ae8ac9c5ced16aab0a60de4ddfdb57a8e, got 91874f9f7ec9500738b5add62e31c6759ab8e097 for blob /var/vcap/data/tmp/bosh-blobstore-external-Get890859432 (00:00:44)
```

**Comment by dpb587** [comment]
Okay, giving up on my tangent idea; been too unproductive with it. Shall we just do this PR then?

**Comment by mrdavidlaing** [comment]
@dpb587, What do you think to giving @wdneto's [`touch every package & job`](https://github.com/logsearch/logsearch-boshrelease/issues/22#issuecomment-46367706) idea?  

That way might force everything to use new blobs?

**Comment by mrdavidlaing** [comment]
Abandoning since @wdneto's [touch every package & job idea worked](https://github.com/logsearch/logsearch-boshrelease/issues/22#issuecomment-46640632)

**Pull request closed without merging**
