### PR TITLE
Decrease persistent disk sizes to 40G

### PR DESCRIPTION
**Pull request by voelzmo**
400G seems a bit overambitious.

### CODE REVIEW

**Comment by poblin-orange** [comment]
True 400Go is too much.
Ideally, this value should be settable in stub manifest, so we can customize the value for each deployment

**Comment by mrdavidlaing** [comment]
We'll take a PR to make this configurable; but 40GB is _waay_ too small for any production like installation.

The default needs to err on the side of too large; since ES dies horribly when it runs out of disk space.

**Comment by voelzmo** [comment]
I agree that there is always the problem with productive use vs. 'just trying it out' or 'dev-usage' for templates.

Not sure I agree that the default should err on the side of being too large. People deploying this to production are probably more willing to adjust some values and go more thorough through the settings than someone who wants to 'just deploy' the ELK stack.

Even if this was configurable, which I again agree is preferable to just setting it to some value, we'd probably argue about the 'default value': Should it be 'production ready' or 'dev-quality'?

**Comment by cromega** [comment]
We are working on a major overhaul of the whole template generation bit. This PR is going to be obsolete very soon.

**Pull request closed without merging**
