### PR TITLE
Release 10

### PR DESCRIPTION
**Pull request by dpb587**
- fixes collectd/python integration (e.g. librato upstream, elasticsearch stats, redis stats)
- new micro-logsearch sample deployment manifest
- allow overriding number of logstash workers via `logstash_parser.workers` (defaults to number of CPUs)
- allow configuring the `idle_flush_time` of logstash parsers via `logstash_parser.idle_flush_time`
- fix redis logging to `/var/vcap/store/queue/stdout` in favor of monit's stdout/stderr
- fix monit being unable to manage the forked redis process

### CODE REVIEW

**Comment by dpb587** [comment]
@mrdavidlaing, ping; this was deployed to meta

**Comment by mrdavidlaing** [comment]
@dpb587, I see that we seem to have [a growing queue on meta](https://metrics.librato.com/dashboards/6266?source=meta.logsearch.io*&duration=259200):
image

Seems we have some unassigned shards in the most recent index:
image

**Comment by mrdavidlaing** [comment]
Aha!  Looks like we ran out of disk space.  I've freed up some space by deleting old data

```
./curator.py --host api.meta.logsearch.io -d 30
```

which deleted about 30 old indexes from 2014-04

**Comment by mrdavidlaing** [comment]
Ok, following purging old indicies, and cleaning up full disks (see https://github.com/logsearch/logsearch-boshrelease/issues/36); the queue is being processed, and the most recent logstash-2014-05-30 index is "green"

However, we still seem to have a problem with unassigned indicies for `logstash-2014.05.23` and `logstash-2014.05.24`.

image

Any ideas?

**Comment by dpb587** [comment]
As discussed elsewhere, I don't believe the full disk issues discussed here are relevant to this release and PR, so, @mrdavidlaing, I think it's okay for this to be merged?

**Comment by mrdavidlaing** [comment]
1.  On reflection, I shouldn't have put the discussion around full disks here. (operation issues belong in our private cityindex/labs-operations repo)
2.  I think we should deploy release-10 to cityindex.logsearch.io and check all works well before merging to live.

**Pull request merged**
