### PR TITLE
add basic authentication and fix logformat bug

### PR DESCRIPTION
**Pull request by yuanzhao**
Since the logsearch website is a public site that everyone can access. The basic authentication is used for kibana login, which denies someone not related from reading our log information. 

Add more log format in the nginx.config.erb, so that the nginx.access.log can show the logs of nginx accessing status.

### CODE REVIEW

**Comment by poblin-orange** [comment]
Basic Auth is good enhancement to the logsearch boshrelease, even if minimalist. Logsearch for Cloudfoundry extension offers an even more compelling option see : https://github.com/logsearch/logsearch-for-cloudfoundry

The solution proposed by @mrdavidlaing includes a cf app, integrated with UAA / cf login, and multitenant logsearch access.
Maybe this PR could be merged with a PR for cloudfoundry logsearch ?
Pierre

**Comment by mrdavidlaing** [comment]
@yuanzhao,

Firstly, thank you for your PR.

Unfortunately, we're not going to be able to merge it in its current state, because it contains 2 separate changes that we would like to discuss separately.
1.  Change to logformat - this is a change we would like to merge, subject to some further discussion.  We've been doing some work with Elasticsearch's slowlog logging, and would like to make sure this change works well with that one.
2.  Basic Authentication.  We've explicitly avoided adding authentication up til this stage, prefering to use IP firewall rules to limit access.  We understand the requirement; but are not quite sure the correct way for it to be implemented, especially given the fact that Kibana 4 comes with its own "basic" authentication.

So, to move forward please could you separate the changes, and raise 2 separate PRs.

Before we can merge, we will also need signed Contributor License Agreements from all the committers on the PR - please see https://github.com/logsearch/licensing for details.

Thanks again; and apologies for not being able to merge these changes at this time.

**Comment by yuanzhao** [comment]
Hi David,

Here is the signed contributor license agreements for the log format pull
request. ​
 1.pdf
https://docs.google.com/a/pivotal.io/file/d/0B-vhTsorAqZzUE56dTVxM0pHQk0/edit?usp=drive_web
​​
 2.pdf
https://docs.google.com/a/pivotal.io/file/d/0B-vhTsorAqZzeElRUk9YSnpkZEk/edit?usp=drive_web
​​
 3.pdf
https://docs.google.com/a/pivotal.io/file/d/0B-vhTsorAqZzREdDWVlpMktqZ0U/edit?usp=drive_web
​​
 4.pdf
https://docs.google.com/a/pivotal.io/file/d/0B-vhTsorAqZzNGprR3VQMTB4akU/edit?usp=drive_web
​

2015-05-05 18:34 GMT+08:00 David Laing notifications@github.com:

> Closed #120 https://github.com/logsearch/logsearch-boshrelease/pull/120.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/logsearch/logsearch-boshrelease/pull/120#event-297086057
> .

## 

Thanks & regards,
Yuan

**Comment by mrdavidlaing** [comment]
@yuanzhao - thanks for the CLA.  All looks good to me.

**Pull request closed without merging**
