### PR TITLE
correcting logic for make_manifest script

### PR DESCRIPTION
**Pull request by haydonryan**
The logic was broken in the make manifest script.

### CODE REVIEW

**Comment by mrdavidlaing** [comment]
@haydonryan,
We're actually not using the `make_manifest` script (its a leftover from the `bosh-gen` template).

Could you expand a bit on your usecase, I'd like to "upgrade" this PR to make this a working feature.

**Comment by haydonryan** [comment]
@mrdavidlaing:

We are wanting to deploy to an AWS environment with multiple CF deployments in one VPC.

Having a sample / base manifest / stub would be awesome.

**Comment by mrdavidlaing** [comment]
@haydonryan, Are you more interested in a sample manifest for AWS, or the spiff "manifest creation" process?

The former we can help with; the latter, not so much

**Comment by haydonryan** [comment]
Aws Manifest is the more important one ;)

Kind Regards,

Haydon Ryan | Solutions Architect | Pivotal Cloud Foundry Services 

Mobile: 415-400-9377 | Email: hryan@pivotal.io

**Comment by mrdavidlaing** [comment]
@haydonryan - I've added a sample AWS manifest based on one of our test clusters to #104.  Lets move this conversation there

**Pull request closed without merging**
