### PR TITLE
Add collectd package/job

### PR DESCRIPTION
**Pull request by mrdavidlaing**
Ship metrics about components in the logsearch cluster to an external metric provider, eg Librato

### CODE REVIEW

**Comment by dpb587** [comment]
@mrdavidlaing, I have a few questions for you Thursday related to uploading blobs and creating a final release. I think this branch is update to date with `cityindex/logsearch` - I went through https://github.com/cityindex/logsearch/compare/23eac341ed2f48c67026ec429b7329fd610b6c50...master comparing and updating as necessary. This doesn't include our logstash parser configuration - we should probably discuss the status of that as well.

**Comment by dpb587** [comment]
Forgot - need to add elasticsearch/redis collectd plugins:
- https://github.com/cityindex/logsearch/blob/d1080650063f1a03446d86816932a105b6382d9c/example/collectd/elasticsearch_logstash.py
- https://github.com/cityindex/logsearch/blob/d1080650063f1a03446d86816932a105b6382d9c/example/collectd/redis_logstash.py

**Comment by mrdavidlaing** [comment]
@dpb587 Sorry for the delay; I missed this update.  I'll review this weekend and we can hopefully go for merge on Monday

**Comment by dpb587** [comment]
@mrdavidlaing, I've updated the PR with the property names we've discussed. I left out `input_type`/`output_type` - I figured we can add those when or if necessary.

The other commit adds back the metric tracking for elasticsearch/redis apis.

Perhaps tomorrow's pairing you can help show me how to finalize this as an (incremental) release?

**Pull request merged**
