### PR TITLE
Better sample manifests

### PR DESCRIPTION
**Pull request by mrdavidlaing**
This PR removes the unused `spiff` based templates, and replaces them with a collection of sample manifests for different clouds / cluster sizes.

It's related to #103

### CODE REVIEW

**Comment by dpb587** [comment]
I consider internal/external IPs, security groups, subnets, S3 buckets/paths, etc to all be internal identifiers which should never be unnecessarily published. I think they should be scrubbed and normalized into test values before rebasing and merging.

**Comment by drnic** [comment]
For anyone looking, https://github.com/cloudfoundry-community/logsearch-boshworkspace has some spiff templates (and uses bosh-workspace to compose them together)

**Comment by dpb587** [comment]
@mrdavidlaing, should this be merged? I commented that I disliked our internal identifiers being published (despite not necessarily confidential), but I'd rather have this merged and closed than hanging around indefinitely.

**Comment by mrdavidlaing** [comment]
This PR has served its purpose of getting something out quickly; I'll close it since its now longer relevant now that projects like https://github.com/cloudfoundry-community/logsearch-boshworkspace exist.

**Pull request closed without merging**
