### PR TITLE
Support customizing elasticsearch environment and options

### PR DESCRIPTION
**Pull request by dpb587**
This would allow us to adjust elasticsearch runtime options (e.g. garbage collection flags) and environment variables (e.g. heap and paths).

### CODE REVIEW

**Comment by dpb587** [comment]
@mrdavidlaing, thoughts or review comments before merging?

**Comment by mrdavidlaing** [comment]
@dpb587 I think there is real value in us shipping with the sane default settings which we have discovered the hard way.

Can you modify this so that:
1.  We use our default elasticsearch runtime options if none are specified in the deploy manifest
2.  The amount of ES heap is dynamic if not specified

**Comment by dpb587** [comment]
@mrdavidlaing, I've made the adjustments. I think in most cases we'll need to copy/override the JVM options with instance-specific ones, but now most of our defaults are there which should at least provide anyone with a head start to debugging and creating their own appropriate settings.

**Comment by mrdavidlaing** [comment]
Perfect.  Lets roll this into a release

**Pull request merged**
