### PR TITLE
Elastic updates

### PR DESCRIPTION
**Pull request by dpb587**
Upgrade elasticsearch to 1.5.2, logstash to 1.5.0

Deployed to:
- [x] meta
- [x] cityindex

### CODE REVIEW

**Comment by dpb587** [comment]
Successfully deployed to meta.

**Comment by dpb587** [comment]
Successfully deployed to cityindex.

@mrdavidlaing, feel free to double check, merge, and release.

**Comment by mrdavidlaing** [comment]
Thx

On Friday, May 22, 2015, Danny Berger notifications@github.com wrote:

> Successfully deployed to cityindex.
> 
> @mrdavidlaing https://github.com/mrdavidlaing, feel free to double
> check, merge, and release.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/logsearch/logsearch-boshrelease/pull/129#issuecomment-104451747
> .

## 

David Laing
logsearch.io - build your own open source cloud logging cluster
http://davidlaing.com

**Comment by mrdavidlaing** [comment]
Looks good to me.  Merging

**Pull request merged**
