### PR TITLE
Integration of Logsearch for cloudfoundry

### PR DESCRIPTION
**Pull request by bonzofenix**

### CODE REVIEW

**Comment by dpb587** [comment]
Hi - it's a good idea to document the l4cf snippets for copy/paste, but I think the readme change would be better made on the [logsearch-for-cloudfoundry repo](https://github.com/logsearch/logsearch-for-cloudfoundry) since people should need/reference that repo for CF stuff. This PR does make me think that we should amend this project's readme with a "see also" section where can link to the l4cf repo for better discovery.

Also, before merging any more `<<: (( merge ))` for spiff, can you please comment on https://github.com/logsearch/logsearch-boshrelease/pull/154#issuecomment-122920155 - I don't want to be introducing more potential issues without better understanding the solution.

**Comment by bonzofenix** [comment]
HI @dpb587 , I agree. I will take a look tomorrow morning at #154 and make sure I move the doc to logsearch-for-cloudfoundry repo. I will submit 2 different PR.

**Comment by bonzofenix** [comment]
@dpb587 We could not reproduce this:
```
./generate_deployment_manifest warden templates/stub.warden.example.yml # It works
```
I think this might be a problem at the stub level. If we know how to reproduce it we can test it but we are not experiencing any issues with this changes.

@bonzofenix

**Comment by bonzofenix** [comment]
@dpb587 This PR should be fixed.

**Comment by bonzofenix** [comment]
@dpb587 I will add the "see also" doc into the README into a separate PR once I get https://github.com/logsearch/logsearch-for-cloudfoundry/pull/58 merged.

**Comment by dpb587** [comment]
Perfect - merged

**Pull request merged**
