### PR TITLE
Out of maintenance notification in README

### PR DESCRIPTION
**Pull request by voelzmo**

### CODE REVIEW

**Comment by axelaris** [comment]
cc @mrdavidlaing

**Comment by dpb587** [comment]
I'm a bit perplexed about this. Why was the repository completely recreated in a different org (not even forked?) rather than continue development here? It's a bit inconvenient, but mostly just terribly confusing, for users and development to continue with logsearch. This repo will continue to show up in search results for quite a while. Can anyone shed a bit more light about the reasons behind the move to cloudfoundry-community?

**Comment by axelaris** [comment]
Hi @dpb587,
I just forwarded you my conversation with David about that. I hope it will help you to understand what's going on ;-)

**Comment by bonzofenix** [comment]
@axelaris can you share that conversation publicly please? At @compozed (Allstate) we are working on a fork that we will eventually OS too as the development here is not making any progress. We are currently finishing the upgrade to ELK 5.0. It would be great to talk with you too to see if there is any chance we could work together on this and where we would work on it as a community. We do not really care where is the repo as long we are all in the same page :).

@dpb587 I completely agree with you this is pretty confusing.

**Comment by axelaris** [comment]
@mrdavidlaing would you mind if I share our conversation here?

In the meantime, @bonzofenix, nothing can stop you from contributing to https://github.com/cloudfoundry-community/logsearch-boshrelease. Please feel free to submit your PR there. If you have any ideas/questions - we can discuss it in #logsearch Slack channel in Cloud Foundry account.

**Comment by axelaris** [comment]
Done.
Sorry, but #259 has been merged instead.

**Pull request closed without merging**
