### PR TITLE
Log "$http_x_forwarded_for" $upstream_addr $upstream_status $upstream_response_time in api access logs

### PR DESCRIPTION
**Pull request by mrdavidlaing**
This is an extension of PR #123 

It:
1.  Updates the way logstash-filters are built and tested to match the other addons, and ensures they work with logstash 1.5.0
2.  Drops the now defunct smoke tests based on lumberjack.
3.  Extends the api job's access logs to include details about `"$http_x_forwarded_for" $upstream_addr $upstream_status $upstream_response_time`
4.  Creates a new set of `nginx-access-v2` logstash filters

### CODE REVIEW

**Comment by mrdavidlaing** [comment]
@dpb587 - I've created the new nginx-access-v2 logstash filters; and included a reference to them in [`src/logstash-filters/default.conf.erb`](https://github.com/logsearch/logsearch-boshrelease/commit/6b0bce036ce54dc17269b82d8ff22e8ecbf5599c#diff-75605f52a8c6a1511cc1be73958f0c5eR16)

How / where do I configure the shipper to update the `@type` to `nginx-access-v2`?

**Comment by dpb587** [comment]
https://github.com/logsearch/logsearch-boshrelease/blob/updated-nginx-logs-filters/jobs/api/templates/logsearch/logs.yml

**Comment by mrdavidlaing** [comment]
@dpb587 - thanks; now our whole conversation you plans for how this works comes flooding back to my jet lagged brain :blush:

**Comment by dpb587** [comment]
@mrdavidlaing - what's the status of this?

**Comment by dpb587** [comment]
I was able to successful deploy this and consider it safe to merge.
- [x] meta
- [x] cityindex

**Pull request merged**
