### PR TITLE
fix Logformat bug

### PR DESCRIPTION
**Pull request by yuanzhao**
Add more log format in the nginx.config.erb, so that the nginx.access.log can show the logs of nginx accessing status.

### CODE REVIEW

**Comment by dpb587** [comment]
Hi Simon+Yuan - can you provide some sample nginx logs from your test deployment of this so we can add the updated logstash parser rules to [`./src/logstash-filters/snippets`](https://github.com/logsearch/logsearch-boshrelease/tree/develop/src/logstash-filters/snippets)? We'll use them to write and commit the tests for immediately after we merge this. (Or, feel free to add them to the PR as `v2` if you already happen to have rules written.) This way deployments will continue to be able to parse the new format after we merge.

**Comment by yuanzhao** [comment]
Hi Danny,

Attachment for your information.

2015-05-07 1:29 GMT+08:00 Danny Berger notifications@github.com:

> Hi Simon+Yuan - can you provide some sample nginx logs from your test
> deployment of this so we can add the updated logstash parser rules to
> ./src/logstash-filters/snippets
> https://github.com/logsearch/logsearch-boshrelease/tree/develop/src/logstash-filters/snippets?
> We'll use them to write and commit the tests for immediately after we merge
> this. (Or, feel free to add them to the PR as v2 if you already happen to
> have rules written.) This way deployments will continue to be able to parse
> the new format after we merge.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/logsearch/logsearch-boshrelease/pull/123#issuecomment-99544972
> .

## 

Thanks & regards,
Yuan

**Comment by dpb587** [comment]
@yuanzhao, attachments from GitHub email replies are not available. Please post them as a regular comment, please - thanks!

**Comment by yuanzhao** [comment]
Here is the singed agreement. Thanks!

img_1420
img_1421
img_1422
img_1423

**Comment by mrdavidlaing** [comment]
@yuanzhao - thanks for the signed CLA.  I've stored a copy; you can delete the comment above if you don't want it to remain public.

Your commits are tagged with authors' `Simon Gao and Yuan Zhao`.  Could you get Simon to also send us a signed CLA please.  (you can just email it direct to david.laing@cityindex.com or david.laing@labs.cityindex.com)

Thanks!

**Comment by dpb587** [comment]
@yuanzhao, were the nginx samples logs in the missing email/attached files as well that you could post as a comment here? Thanks

**Comment by yuanzhao** [comment]
can we signed our names on a same copy? 
simon

**Comment by mrdavidlaing** [comment]
@yuanzhao - unfortunately no; I need  separate signed copy from each of you.  However, I only need a scan of the last page with the signature.

**Comment by yuanzhao** [comment]
@mrdavidlaing, here is Simon Gao's signature in the attachment.
simon

**Comment by mrdavidlaing** [comment]
@yuanzhao, perfect, thanks!

Now, lets get this PR merged.

Could you provide some sample nginx logs from your test deployment ( 1 - 5 lines added as a comment here should be fine ), so we can update the associated logstash parser rules at [`./src/logstash-filters/snippets`](https://github.com/logsearch/logsearch-boshrelease/tree/develop/src/logstash-filters/snippets).

Thanks

**Comment by yuanzhao** [comment]
@mrdavidlaing  here is the nginx log, hope it will be helpful.

```
10.10.66.43 - - [07/May/2015:01:52:40 +0000]  401 "GET / HTTP/1.1" 596 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   -  -  -
10.10.66.43 - birdnest [07/May/2015:01:52:55 +0000]  200 "GET / HTTP/1.1" 937 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127.0.0.1:5601  200  0.008
10.10.66.43 - birdnest [07/May/2015:01:52:55 +0000]  304 "GET /bower_components/requirejs/require.js?_b=5930 HTTP/1.1" 0 "https://logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127.0.0.1:5601  304  0.004
10.10.66.43 - birdnest [07/May/2015:01:52:55 +0000]  304 "GET /styles/main.css?_b=5930 HTTP/1.1" 0 "https://logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127.0.0.1:5601  304  0.002
10.10.66.43 - birdnest [07/May/2015:01:52:55 +0000]  304 "GET /images/initial_load.gif HTTP/1.1" 0 "https://logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127.0.0.1:5601  304  0.002
10.10.66.43 - birdnest [07/May/2015:01:52:56 +0000]  304 "GET /require.config.js?_b=5930 HTTP/1.1" 0 "https://logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127.0.0.1:5601  304  0.002
@
"Downloads/nginx_access.log.api.0" 27L, 7260C
10.10.66.43 - - [07/May/2015:01:52:40 +0000]  401 "GET / HTTP/1.1" 596 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   -  -  -
10.10.66.43 - birdnest [07/May/2015:01:52:55 +0000]  200 "GET / HTTP/1.1" 937 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127.0.0.1:5601  200  0.008
10.10.66.43 - birdnest [07/May/2015:01:52:55 +0000]  304 "GET /bower_components/requirejs/require.js?_b=5930 HTTP/1.1" 0 "https://logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127.0.0.1:5601  304  0.004
10.10.66.43 - birdnest [07/May/2015:01:52:55 +0000]  304 "GET /styles/main.css?_b=5930 HTTP/1.1" 0 "https://logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_99
_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216..
253.193.158"   127.0.0.1:5601  304  0.002
10.10.66.43 - birdnest [07/May/2015:01:52:55 +0000]  304 "GET /images/initial_load.gg
if HTTP/1.1" 0 "https://logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_99
_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216..
253.193.158"   127.0.0.1:5601  304  0.002
10.10.66.43 - birdnest [07/May/2015:01:52:56 +0000]  304 "GET /require.config.js?_b==
5930 HTTP/1.1" 0 "https://logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 100
_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "211
6.253.193.158"   127.0.0.1:5601  304  0.002
@
@                                                                                   )
@
10.10.66.43 - - [07/May/2015:01:52:40 +0000]  401 "GET / HTTP/1.1" 596 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   -  -  -
10.10.66.43 - birdnest [07/May/2015:01:52:55 +0000]  200 "GET / HTTP/1.1" 937 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127.0.0.1:5601  200  0.008
10.10.66.43 - birdnest [07/May/2015:01:52:55 +0000]  304 "GET /bower_components/requirejs/require.js?_b=5930 HTTP/1.1" 0 "https://logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OO
S X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "2166
.253.193.158"   127.0.0.1:5601  304  0.004
10.10.66.43 - birdnest [07/May/2015:01:52:55 +0000]  304 "GET /styles/main.css?_b=5930 HTTPP
/1.1" 0 "https://logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKii
t/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127.0..
0.1:5601  304  0.002
10.10.66.43 - birdnest [07/May/2015:01:52:55 +0000]  304 "GET /images/initial_load.gif HTTPP
/1.1" 0 "https://logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKii
t/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127.0..
0.1:5601  304  0.002
10.10.66.43 - birdnest [07/May/2015:01:52:56 +0000]  304 "GET /require.config.js?_b=5930 HTT
TP/1.1" 0 "https://logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebb
Kit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127..
0.0.1:5601  304  0.002
10.10.66.43 - birdnest [07/May/2015:01:52:56 +0000]  304 "GET /styles/theme/elk.ico HTTP/1..
1" 0 "https://logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/55
37.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127.0.0.11
:5601  304  0.002
@
10.10.66.43 - - [07/May/2015:01:52:40 +0000]  401 "GET / HTTP/1.1" 596 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   -  -  -
10.10.66.43 - birdnest [07/May/2015:01:52:55 +0000]  200 "GET / HTTP/1.1" 937 "-" "Mozilla/5.0 (Macintoo
sh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" ""
216.253.193.158"   127.0.0.1:5601  200  0.008
10.10.66.43 - birdnest [07/May/2015:01:52:55 +0000]  304 "GET /bower_components/requirejs/require.js?_bb
=5930 HTTP/1.1" 0 "https://logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit//
537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127.0.0.1:5601  304
 0.004
10.10.66.43 - birdnest [07/May/2015:01:52:55 +0000]  304 "GET /styles/main.css?_b=5930 HTTP/1.1" 0 "httt
ps://logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gee
cko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127.0.0.1:5601  304  0.002
10.10.66.43 - birdnest [07/May/2015:01:52:55 +0000]  304 "GET /images/initial_load.gif HTTP/1.1" 0 "httt
ps://logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gee
cko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127.0.0.1:5601  304  0.002
10.10.66.43 - birdnest [07/May/2015:01:52:56 +0000]  304 "GET /require.config.js?_b=5930 HTTP/1.1" 0 "hh
ttps://logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127.0.0.1:5601  304  0.002
10.10.66.43 - birdnest [07/May/2015:01:52:56 +0000]  304 "GET /styles/theme/elk.ico HTTP/1.1" 0 "https::
//logsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Geckoo
) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127.0.0.1:5601  304  0.002
10.10.66.43 - birdnest [07/May/2015:01:52:56 +0000]  304 "GET /index.js?_b=5930 HTTP/1.1" 0 "https://loo
gsearch.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chh
rome/42.0.2311.135 Safari/537.36" "216.253.193.158"   127.0.0.1:5601  3
10.10.66.43 - - [07/May/2015:01:52:40 +0000]  401 "GET / HTTP/1.1" 596 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36" "216.253.193.158"   -  -  -
```

**Comment by mrdavidlaing** [comment]
@yuanzhao - For some reason we seem to have lost access to your forked repo which this PR came from.

I've cherry picked your changes into PR #130; and will merge them as part of that.

**Pull request closed without merging**
