### PR TITLE
remove merge from api job

### PR DESCRIPTION
**Pull request by acrlewis**
Removed merge in API job templates section in logsearch-jobs.yml. 

This was causing Error 40001: Required property `name' was not specified in object ({}) in release deployment.

### CODE REVIEW

**Comment by dpb587** [comment]
@bonzofenix, @malston - it seems like #150 which added the merging is causing problems in this situation. I'm not very familiar with spiff, so I can't really comment to an alternative fix aside from reverting your original PR. Is there something we can do to provide a default merge value for templates to avoid this error? It would be nice to keep the template-merging capabilities you've added.

See also #153.

**Comment by bonzofenix** [comment]
@dpb587, @acrlewis We could not reproduce this:

```
./generate_deployment_manifest warden templates/stub.warden.example.yml # It works
```

I think this might be a problem at the stub level. If we know how to reproduce it we can test it but we are not experiencing any issues with this changes.

@bonzofenix

**Comment by dpb587** [comment]
@acrlewis, it sounds like it's an issue with your local stubs. Perhaps take a second look at them to make sure spiff merging behaviors aren't being confused. I'm going to close this PR since it isn't the correct fix right now.

If you still need help, let's continue the discussion back on your original issue, #153, and I'll need more details about your stub files to debug further.

**Comment by acrlewis** [comment]
Sorry for the delay, I used the example stubs as well

```
./generate_deployment_manifest aws templates/stub.aws.example.yml

jobs:
......
  templates:
  - {}
  - name: elasticsearch
  - name: api
  - name: kibana

```

```
---
meta:
  availability_zone: ap-northeast-1a 

releases:
- name: logsearch
  version: latest

name: logsearch-ashamalama
director_uuid: 12345-12345-12345-12345

resource_pools:
- name: logsearch_api
  cloud_properties:
    elbs: 
    - logsearch-api

- name: logsearch_ingestor
  cloud_properties:
    elbs:
    - logsearch-ingestor

- name: logsearch_elasticsearch
  cloud_properties:
    elbs:
    - logsearch-elasticsearch

networks:
- name: default 
  type: manual
  subnets:
  - range: 10.10.48.0/24
    gateway: 10.10.48.1
    cloud_properties:
       subnet: subnet-12345
       security_groups: [logsearch]
    dns:
    - 10.10.0.2
    reserved:
    - 10.10.48.2 - 10.10.48.9
    static:
    - 10.10.48.10 - 10.10.48.55
```

```
./generate_deployment_manifest vsphere templates/stub.vsphere.example.yml

jobs:
......
  templates:
  - {}
  - name: elasticsearch
  - name: api
  - name: kibana
```

```
---
meta:

releases:
- name: logsearch
  version: latest

name: logsearch-ashamalama
director_uuid: 12345-12345-12345-12345


networks:
- name: default
  subnets:
  - range: 10.10.48.0/24
    gateway: 10.10.48.1
    dns:
    - 10.10.0.2
    reserved:
    - 10.10.48.2 - 10.10.48.9
    static:
    - 10.10.48.10 - 10.10.48.55
    cloud_properties:
      name: vblk-pcf-test-mgmt

```

**Comment by acrlewis** [comment]
```
./generate_deployment_manifest warden templates/stub.warden.example.yml
```

```
jobs:
......
  templates:
  - {}
  - name: elasticsearch
  - name: api
  - name: kibana
```

```
---
meta:
  environment: (( name ))

name: logsearch
director_uuid: 12345-678910

```

**Comment by dpb587** [comment]
Oh, you're definitely right, @acrlewis - sorry for my misunderstanding. I didn't look closely enough at the output of the templates.

@bonzofenix, I can confirm the empty `- {}` values are in the output when only using the committed files. What do we need to change?

```
$ spiff -v
spiff version 1.0.6
$ ./generate_deployment_manifest aws templates/stub.aws.example.yml
...snip...
  resource_pool: logsearch_api
  templates:
  - {}
  - name: elasticsearch
...snip...
$ ./generate_deployment_manifest warden templates/stub.warden.example.yml
...snip...
  resource_pool: logsearch_api
  templates:
  - {}
  - name: elasticsearch
...snip...
  version: latest
- {}
resource_pools:
...snip...
$ ./generate_deployment_manifest vsphere templates/stub.vsphere.example.yml
...snip...
  resource_pool: logsearch_api
  templates:
  - {}
  - name: elasticsearch
...snip...
```

**Comment by bonzofenix** [comment]
@dpb587 , @acrlewis  You guys are wright, working on this.

**Comment by bonzofenix** [comment]
https://github.com/logsearch/logsearch-boshrelease/pull/158 Should fixes this. There is actually an issue on spiff on this: https://github.com/cloudfoundry-incubator/spiff/issues/27

**Comment by mrdavidlaing** [comment]
@acrlewis - sorry to be pedantic, but I'm going to need a signed CLA from you (or your company) before we can merge this change.  If you wouldn't mind, see https://github.com/logsearch/licensing/ for details

**Comment by acrlewis** [comment]
No problem @mrdavidlaing, is Pivotal already covered under the CLA?

**Comment by mrdavidlaing** [comment]
@acrlewis - yes; we have a corporate CLA from pivotal, so you are covered.  Need to find a better way of managing who has signed a CLA an who hasn't...

**Comment by acrlewis** [comment]
sweet, nice work team

**Pull request closed without merging**
