### PR TITLE
Set ulimit -n 64000 on elasticsearch

### PR DESCRIPTION
**Pull request by dpb587**
Issue #93

### CODE REVIEW

**Comment by dpb587** [comment]
@mrdavidlaing, is `ulimit` "bosh" friendly? Or is there a more cross-OS friendly way that you've seen releases use?

**Comment by dpb587** [comment]
Also, we really should be running all our jobs under the `vcap` user; but that should probably be a separate issue.

**Comment by mrdavidlaing** [comment]
@dpb587 - `ulimit` is the way to go.  BOSH is pretty much confined to running on Ubuntu & CentOS; I wouldn't worry about trying to make logsearch-boshrelease work across anything more than those (and actually, I'd only worry about Ubuntu unless someone complains)

**Comment by dpb587** [comment]
Deployed to meta. Before and after...

```
$ wget -qO- api.meta.logsearch.io:9200/_nodes/_all/process | jq '.nodes | map(select("false" != .attributes.data)) | map({ "key" : .name , "value" : .process.max_file_descriptors }) | sort_by(.key) | from_entries'
{
  "elasticsearch_persistent-z1/0": 4096,
  "elasticsearch_persistent/0": 4096,
}
$ !!
{
  "elasticsearch_persistent-z1/0": 64000,
  "elasticsearch_persistent/0": 64000
}
```

**Pull request merged**
