### PR TITLE
Added a really primitive health test for elastic search to smoke/acce…

### PR DESCRIPTION
**Pull request by geofffranks**
…ptance tests

### CODE REVIEW

**Comment by geofffranks** [comment]
Will this run into issues if someone tries to run the tests shortly after an upgrade (data nodes might be shuffling shards around and putting status in a yellow state)?

**Comment by dpb587** [comment]
Thanks for the PR! This is a good sanity test to include.

If elasticsearch is only shuffling and rebalancing shards around, the status shouldn't drop a color. So, once the cluster is at least yellow, data should be sufficiently loaded for this sort of test to run.

We're also working on some separate changes in this file on the [test_e2e_errand_timing_bug](https://github.com/logsearch/logsearch-boshrelease/tree/test_e2e_errand_timing_bug) branch, so once we finish up with those, we'll be able to get this merged.

In the meantime, I don't think we have a CLA from you - would you mind [sending](https://github.com/logsearch/licensing) us yours so we can merge this once it's ready?

**Comment by mrdavidlaing** [comment]
@geofffranks - CLA received, thanks!  No more legal barriers to getting this PR merged

**Comment by mrdavidlaing** [comment]
I'm just going to merge this now; it shouldn't interfere with the refactoring I'm doing at https://github.com/logsearch/logsearch-boshrelease/pull/151

**Pull request merged**
