### PR TITLE
Fix logsearch-jobs template

### PR DESCRIPTION
**Pull request by Infra-Red**
Fix manifest generation process, there should be grab operation instead of concat.

### CODE REVIEW

**Comment by mrdavidlaing** [comment]
@cromega - I seem to recall there was a reason we used `concat` instead of `grab`.  Can you remember?

**Comment by mrdavidlaing** [comment]
@Infra-Red - Thanks!

I don't seem to have a signed CLA from you; which we'll need before we can merge this.

Please could you print & sign the relevant CLA from https://github.com/logsearch/licensing#signing-the-contributors-license-agreement and forward to david.laing@labs.cityindex.com

Thanks!

**Comment by axelaris** [comment]
Hi @mrdavidlaing, we're working with @Infra-Red for the same company (Altoros).
The CLA is already signed by company.

**Comment by mrdavidlaing** [comment]
@axelaris - Hello!  Excellent.  CLA sorted then

**Comment by cromega** [comment]
@Infra-Red: thanks!

**Pull request merged**
